version: '3'

silent: true

vars:
  module: github.com/wisbery/tarolas

tasks:

  build:
    desc: Build debug
    cmds:
      - cmd: go build {{.module}}

  clean:
    desc: Clean built artefacts
    cmds:
      - cmd: go clean

  fmt:
    desc: Run formatter
    cmds:
      - cmd: go fmt {{.module}} ./...

  install:
    desc: Build release
    cmds:
      - cmd: go install {{.module}}

  run:
    desc: Run release
    cmds:
      - cmd: go run {{.module}}

  test:
    desc: Run all tests
    cmds:
      - cmd: go test {{.module}} ./...

  uninstall:
    desc: Unstall release version
    cmds:
      - cmd: rm ~/go/bin/tarolas
    ignore_error: true

  vet:
    desc: Run linter
    cmds:
      - cmd: go vet {{.module}} ./...
    ignore_error: true
